name: Puppeteer Tests
on: [push, pull_request]

# https://hub.docker.com/r/cypress/browsers/tags
jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node20.11.0-chrome119-ff118
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g pnpm
      - run: pnpm install
      - name: Install correct Chrome version
        run: npx puppeteer-core browsers install chrome@119.0.6045.105
      - name: Run Puppeteer tests
        run: pnpm run e2e

