name: Puppeteer Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Create report directory
        run: mkdir -p test-results
      - name: Run Puppeteer tests
        run: pnpm run e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: puppeteer-report
          path: puppeteer-report/
          retention-days: 30
