name: Puppeteer Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node-22.14.0-chrome-133.0.6943.53-1-ff-135.0-edge-133.0.3065.59-1
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g pnpm
      - run: pnpm install
      - name: Run Puppeteer tests
        run: pnpm run e2e
