name: Puppeteer Tests
on: [push, pull_request]

# https://hub.docker.com/r/cypress/browsers/tags
jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node22.14.0-chrome133-ff135 # Node 22
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g pnpm
      - run: pnpm install
      - name: Install Chrome
        run: npx puppeteer-core browsers install chrome@133.0.6696.123  # Version matching Docker image
      - name: Run Puppeteer tests
        run: pnpm run e2e


