name: Puppeteer Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node-20.14.0-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g pnpm
      - run: pnpm install
      - name: Run Puppeteer tests
        run: pnpm run e2e
